baseURL = 'https://nico-series.github.io/'
languageCode = 'en-us'
title = 'nico-series'
theme = 'archie-nico-ver'
[params]
    mode = 'toggle'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4